### PR TITLE
Fix for linux where it fails on init of PozyxSerial() and fix for denormalized quaternion

### PR DESCRIPTION
**Pull request by sven-bock**
checking OS in init to handle the serial port differently.
printed exception, as the default error message was misleading.

### CODE REVIEW

**Comment by sven-bock** [comment]
As the quaternions from the pozyx library are not normalized, they cause some troubles in ROS, depending on the quaternion and are not usable.
This is one of the error messages from ROS:
`Error:   TF_DENORMALIZED_QUATERNION: Ignoring transform for child_frame_id "pozyx" from authority "unknown_publisher" because of an invalid quaternion in the transform (0.346619 0.707642 0.384827 0.503662)`
I have patched the lib.py

**Comment by laurentva** [comment]
Hey Sven,

Thanks for the PR! Could you make a separate function getNormalizedQuaternion instead of changing the current one and PR that? 

What linux are you using? It's more likely that your pyserial library (eg on an RPi, installed by default) is out of date. You can fix this using pip install pyserial --upgrade. As for the exception handling, that will be expanded in the next release and I'll use that Exception as exc for sure.

**Comment by arotyramel** [comment]
Hey Laurent,
right, a separate function is even smarter. I ll do the changes. 

I am using Ubuntu 16.04 with ROS Kinetic. I have checked the pyserial version that is currently. It is 3.0.1.

**Comment by laurentva** [comment]
Hey Sven,

Cool, thanks! Is it possible to PR into the develop branch? I'll make a new release later today.

**Comment by sven-bock** [comment]
Hey Laurent,

please check, if it is now as you expect it to be.

**Comment by laurentva** [comment]
Hey Sven,

I've been looking into your issue where you did some os handling, and tried out PySerial version 3.0.1, but I'm not having an issue. What error did you get that made you change that? PySerial itself already does system differentiation to determine which kinde of Serial you actually import, which is pretty cool.  See https://github.com/pyserial/pyserial/blob/master/serial/__init__.py and SerialBase in
https://github.com/pyserial/pyserial/blob/master/serial/serialutil.py, followed by Serial in https://github.com/pyserial/pyserial/blob/master/serial/serialposix.py if you're interested.

ROS is still on Python 2, I guess?

**Comment by arotyramel** [comment]
Hey Laurent,

ah. I remember know when I had the problem. I was running it on a
turtlebot3 which had a Raspbian Jessie (Debian8). There I had the  problem
that the parameter "write_timeout" was unknown.

self.ser = Serial(port, baudrate, timeout=timeout,*
write_timeout=write_timeout*)

I have just checked the sources for the used pyserial (2.6-1.1)
https://packages.debian.org/source/jessie/pyserial
Actually it is quite interessting. The parameter is there, it is  just
spelled differently. They used camel case instead of underscores.....

*writeTimeout* instead of *write_timeout*

=)

So I have to admit that my fix to check for the OS does not bring the
desired effect, we should better check for the version.

**Comment by laurentva** [comment]
I'm now doing a version check and warning the user to upgrade to 3.0+ if possible. I'd rather not add support for PySerial < 3.0 but seeing how it's default on RPis it's not easy to avoid.

**Pull request closed without merging**
